### ISSUE TITLE
Ignored rotation lock

### ISSUE THREAD

**Issue by pkshah2017** [ajivoin/flappy-mckain-issue-tracker#6]
The app will rotate regardless of whether or not you have rotation lock enabled.

**Comment by ajivoin** [comment]
This is a bug with Unity, there might be a workaround to fix it though. I'll look into it.

**Comment by ajivoin** [comment]
The package [HiddenVariableStudios/unity-android-rotation-lock](https://github.com/HiddenVariableStudios/unity-android-rotation-lock/) fixes this.

It will be fixed in the next release.
